version: '3.8'

services:
  data-service:  # Meaningful name for app1
    build:
      context: ./data-service  # Updated to reflect new name
    container_name: data-service-container
    networks:
      - app-network
    ports:
      - "8080:8080"  # Expose port 8080 for the server

  client-service:  # Meaningful name for app2
    build:
      context: ./client-service  # Updated to reflect new name
    container_name: client-service-container
    networks:
      - app-network
    depends_on:
      - data-service  # Ensure the data service is started before client-service

networks:
  app-network:
    driver: bridge
